import { type App, type Component, createSSRApp, h } from "vue";
import { renderToString, type SSRContext } from "vue/server-renderer";
import { normalizeVueIslandApp } from "./app.js";
import type { ViewHook } from "./phoenixFallbackTypes";
import type { VueIslandOptions, VueArgs } from "./types.js";
import { mapValues } from "./utils.js";

type Components = Record<string, Component>;
type Manifest = Record<string, string[]>;

const basename = (path: string) => path.slice(path.lastIndexOf("/") + 1);

const mockLive: Partial<Omit<ViewHook, "el">> & {
  el: {};
  liveSocket: {};
  removeHandleEvent: () => void;
  upload: () => void;
  uploadTo: () => void;
  vue: Omit<VueArgs, "app"> & { app: object };
} = {
  el: {},
  liveSocket: { socket: { connectionState: () => "closed" } } as any,
  pushEvent: () => Promise.resolve(0),
  pushEventTo: () => Promise.resolve([]),
  handleEvent: () => ({ event: "", callback: () => {} }),
  removeHandleEvent: () => {},
  upload: () => {},
  uploadTo: () => {},
  vue: {
    props: {},
    slots: {},
    app: {},
  },
};
export const getRender = (
  componentsOrApp: Components | VueIslandOptions,
  manifest: Manifest = {},
) => {
  const { resolve, setup } = normalizeVueIslandApp(componentsOrApp);

  return async (
    name: string,
    props: Record<string, any>,
    slots: Record<string, string>,
  ) => {
    const component = await resolve(name);
    const slotComponents = mapValues(
      slots,
      (html) => () => h("div", { innerHTML: html }),
    );
    const app = setup({
      createApp: createSSRApp,
      component,
      props,
      slots: slotComponents,
      plugin: {
        install: (app: App) => {
          // we don't want to mount the app in SSR
          app.mount = (..._args: unknown[]): any => undefined;
          // we don't have hook instance in SSR, so we need to mock it
          app.provide("_live_islands_vue", Object.assign({}, mockLive));
        },
      },
      // @ts-ignore - this is just an IDE issue. the compiler is correctly processing this with the server tsconfig
      el: {},
      ssr: true,
    });

    if (!app) throw new Error("Setup function did not return a Vue app!");

    const ctx: SSRContext = {};
    const html = await renderToString(app, ctx);

    // the SSR manifest generated by Vite contains module -> chunk/asset mapping
    // which we can then use to determine what files need to be preloaded for this
    // request.
    const preloadLinks = renderPreloadLinks(ctx.modules, manifest);
    // easy to split structure
    return preloadLinks + "<!-- preload -->" + html;
  };
};

export function renderPreloadLinks(
  modules: SSRContext["modules"],
  manifest: Manifest,
) {
  let links = "";
  const seen = new Set();
  modules.forEach((id: string) => {
    const files = manifest[id];
    if (files) {
      files.forEach((file) => {
        if (!seen.has(file)) {
          seen.add(file);
          const filename = basename(file);
          if (manifest[filename]) {
            for (const depFile of manifest[filename]) {
              links += renderPreloadLink(depFile);
              seen.add(depFile);
            }
          }
          links += renderPreloadLink(file);
        }
      });
    }
  });
  return links;
}

export function renderPreloadLink(file: string) {
  if (file.endsWith(".js") || file.endsWith(".mjs")) {
    return `<link rel="modulepreload" crossorigin href="${file}">`;
  } else if (file.endsWith(".css")) {
    return `<link rel="stylesheet" href="${file}">`;
  } else if (file.endsWith(".woff")) {
    return ` <link rel="preload" href="${file}" as="font" type="font/woff" crossorigin>`;
  } else if (file.endsWith(".woff2")) {
    return ` <link rel="preload" href="${file}" as="font" type="font/woff2" crossorigin>`;
  } else if (file.endsWith(".gif")) {
    return ` <link rel="preload" href="${file}" as="image" type="image/gif">`;
  } else if (file.endsWith(".jpg") || file.endsWith(".jpeg")) {
    return ` <link rel="preload" href="${file}" as="image" type="image/jpeg">`;
  } else if (file.endsWith(".png")) {
    return ` <link rel="preload" href="${file}" as="image" type="image/png">`;
  } else {
    // TODO
    return "";
  }
}
